services:
  eb-replication:
    image: replication-eb-replication:latest
    build: .
    platform: linux/amd64
    container_name: eb-replication-env
    volumes:
      # Mount only output directories
      - ./results:/app/results
      - ./assets:/app/assets
      - ./data/raw:/app/data/raw
      - ./data/processed:/app/data/processed
      - ./data/simulated_posterior_means:/app/data/simulated_posterior_means
      # Mount MOSEK license from project directory
      - ./mosek.lic:/app/mosek.lic:ro
    environment:
      - NUM_CORES=4
      - PYTHONPATH=/app
      # MOSEK license environment variable
      - MOSEKLM_LICENSE_FILE=/app/mosek.lic
    working_dir: /app
    # Keep container running for interactive use
    tty: true
    stdin_open: true
    # Optional: expose Jupyter port if needed
    ports:
      - "8888:8888"

  # Minimal container that mounts only raw data (no processed or simulated outputs).
  # Useful for validating scripts that should not see generated Monte Carlo files.
  eb-replication-test:
    image: replication-eb-replication:latest
    build: .
    platform: linux/amd64
    container_name: eb-replication-test-env
    volumes:
      - ./data/raw:/app/data/raw # Mount raw data only and not simulated posterior means
      # Mount outputs to empty scratch directories
      - ./data/processed_empty:/app/data/processed
      - ./results_empty:/app/results
      - ./assets_empty:/app/assets
      - ./data/simulated_posterior_means_empty:/app/data/simulated_posterior_means
      # Mount MOSEK license from project directory
      - ./mosek.lic:/app/mosek.lic:ro
    environment:
      - NUM_CORES=4
      - PYTHONPATH=/app
      # MOSEK license environment variable
      - MOSEKLM_LICENSE_FILE=/app/mosek.lic
    working_dir: /app
    # Keep container running for interactive use
    tty: true
    stdin_open: true
